# Generated by Django 3.0.6 on 2020-06-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
