# Generated by Django 3.0.6 on 2020-06-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_pay_hist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pay_hist',
        ),
    ]
