# Generated by Django 3.0.6 on 2020-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_delete_pay_hist'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay_hist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('order_id', models.CharField(max_length=25)),
                ('pay_id', models.CharField(max_length=25)),
                ('amnt', models.IntegerField(default=0)),
            ],
        ),
    ]
