# Generated by Django 3.0.6 on 2020-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_pay_hist_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_hist',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
