# Generated by Django 3.0.6 on 2020-06-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200603_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_hist',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
