# Generated by Django 3.0.6 on 2020-06-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200603_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_hist',
            name='date_ordered',
        ),
        migrations.AddField(
            model_name='pay_hist',
            name='order date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
