# Generated by Django 3.0.6 on 2020-06-03 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200603_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay_hist',
            name='order date',
        ),
        migrations.AddField(
            model_name='pay_hist',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 20, 14, 21, 528195)),
        ),
    ]
