# Generated by Django 3.0.6 on 2020-06-03 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200603_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay_hist',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 20, 15, 52, 36858), editable=False),
        ),
    ]
