# Generated by Django 3.0.6 on 2020-06-03 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(auto_created=True, default=uuid.UUID('99fc2e26-a573-11ea-bd84-7440bb36fee8'), max_length=200)),
                ('recipients', models.CharField(blank=True, max_length=2000, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
