# Generated by Django 3.0.6 on 2020-06-03 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('a8206ca8-a573-11ea-9134-7440bb36fee8'), max_length=200),
        ),
    ]
