# Generated by Django 3.0.6 on 2020-06-03 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0002_auto_20200603_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('ed6870f4-a5a0-11ea-b9fe-7440bb36fee8'), max_length=200),
        ),
    ]
