# Generated by Django 3.0.6 on 2020-06-03 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0003_auto_20200603_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('65f0d866-a5a4-11ea-a7e6-7440bb36fee8'), max_length=200),
        ),
    ]
