# Generated by Django 3.0.6 on 2020-06-03 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0005_auto_20200603_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('bdd276b6-a5a5-11ea-9029-7440bb36fee8'), max_length=200),
        ),
    ]
