# Generated by Django 3.0.6 on 2020-06-03 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0007_auto_20200603_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('2a8b968c-a5a7-11ea-adea-7440bb36fee8'), max_length=200),
        ),
    ]
