# Generated by Django 3.0.6 on 2020-06-03 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0008_auto_20200603_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('5f73c1a4-a5a7-11ea-96c7-7440bb36fee8'), max_length=200),
        ),
    ]
