# Generated by Django 3.0.6 on 2020-06-03 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0011_auto_20200603_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('ebfb3476-a5a8-11ea-bee5-7440bb36fee8'), max_length=200),
        ),
    ]
