# Generated by Django 3.0.6 on 2020-06-03 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0012_auto_20200603_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('ab824746-a5a9-11ea-9559-7440bb36fee8'), max_length=200),
        ),
    ]
