# Generated by Django 3.0.6 on 2020-06-03 14:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0013_auto_20200603_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('f9c64dca-a5a9-11ea-b32c-7440bb36fee8'), max_length=200),
        ),
    ]
