# Generated by Django 3.0.6 on 2020-06-04 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0014_auto_20200603_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_model',
            name='user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('4b1f8940-a633-11ea-aeec-7440bb36fee8'), max_length=200),
        ),
    ]
