# Generated by Django 3.0.6 on 2020-06-04 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0015_auto_20200604_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_model',
            name='recipients',
        ),
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('0567a4a4-a678-11ea-a61b-7440bb36fee8'), max_length=200),
        ),
    ]
