# Generated by Django 3.0.6 on 2020-06-04 15:35

from django.db import migrations, models
import multi_email_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0016_auto_20200604_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_model',
            name='recipients',
            field=multi_email_field.fields.MultiEmailField(null=True),
        ),
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('0e0b4152-a679-11ea-b34d-7440bb36fee8'), max_length=200),
        ),
    ]
