# Generated by Django 3.0.6 on 2020-06-04 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('es', '0017_auto_20200604_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_model',
            name='recipients',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='email_model',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.UUID('d581af3e-a679-11ea-8ca6-7440bb36fee8'), max_length=200),
        ),
    ]
